version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nexus-db
    environment:
      - POSTGRES_USER=nexususer
      - POSTGRES_PASSWORD=nexuspassword
      - POSTGRES_DB=nexus
    ports:
      - "5432:5432"
    volumes:
      - nexus-data:/var/lib/postgresql/data

volumes:
  nexus-data: